import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import type { CloudflareBindings } from "../../env.js";
import { accessibilitySuggestInputSchema } from "../../application/dto/accessibility.dto.js";
import { rateLimitMiddleware } from "../middleware/rate-limit.middleware.js";
import type { SuggestAccessibilityUseCase } from "../../application/use-cases/accessibility/suggest-accessibility.use-case.js";

interface AccessibilityRouteDeps {
  suggestAccessibility: SuggestAccessibilityUseCase;
}

export function createAccessibilityRoutes(deps: AccessibilityRouteDeps) {
  const app = new Hono<{ Bindings: CloudflareBindings }>();

  /**
   * POST /api/v1/accessibility/suggest
   *
   * Accepts an axe-core / WCAG violation payload and returns structured
   * remediation advice generated by the user's configured AI provider.
   *
   * Rate-limited via RATE_LIMITER_PROXY (20 req/60 s per user+IP).
   */
  app.post(
    "/suggest",
    rateLimitMiddleware("RATE_LIMITER_PROXY"),
    zValidator("json", accessibilitySuggestInputSchema, (result, c) => {
      if (!result.success) {
        return c.json(
          { error: "Validation error", details: result.error.issues },
          400,
        );
      }
    }),
    async (c) => {
      const userId = c.get("userId") as string;
      const ip = c.req.header("CF-Connecting-IP") ?? null;
      const input = c.req.valid("json");

      const output = await deps.suggestAccessibility.execute(userId, ip, input);

      return c.json(output, 200);
    },
  );

  return app;
}
